const assert=require('node:assert/strict');
const classes=new Map();
global.HTMLElement=class{attachShadow(){return this.shadowRoot={innerHTML:'',querySelectorAll:()=>[],querySelector:()=>null}}};
global.customElements={get:n=>classes.get(n),define:(n,c)=>classes.set(n,c)};
global.window={customCards:[]};
require('../../custom_components/soundsticks5/frontend/soundsticks5-lovelace.js');
const c=new (classes.get('soundsticks5-lovelace-card'))();
const events={},calls=[];
c._hass={language:'zh',states:{'select.preset':{state:'test',attributes:{options:['test']}}},callService:async(...a)=>calls.push(a)};
c._entities={preset:'select.preset'};
c.shadowRoot.querySelector=s=>({addEventListener:(event,fn)=>events[s]=fn});
(async()=>{
 c._render();
 assert.equal(c._selectedPreset,'test');
 assert.match(c.shadowRoot.innerHTML,/data-preset-apply/);
 events['[data-preset-select]']({target:{value:'test'}});
 assert.equal(calls.length,0);
 await events['[data-preset-apply]']();
 await events['[data-preset-apply]']();
 assert.equal(calls.length,2);
 assert.deepEqual(calls[0],['select','select_option',{entity_id:'select.preset',option:'test'}]);
 c._hass.callService=async()=>{throw Error('offline')};
 await events['[data-preset-apply]']();
 assert.equal(c._presetBusy,false);
 assert.match(c._presetMessage,/应用未完成/);
 assert.match(c._speedWaves(1),/>~</);
 assert.match(c._speedWaves(2),/>≈</);
 assert.equal((c._speedWaves(3).match(/<i>~<\/i>/g)||[]).length,3);
 console.log('PASS: selecting does not apply, single preset reapplies, errors clear busy state, consistent wave counts');
})().catch(e=>{console.error(e);process.exitCode=1});
